name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    uses: GroepOnline/.github/.github/workflows/ci.yml@64b52a28a0720444572737cb882f37bac253dc79
    with:
      language: node
